repos:
-   repo: https://github.com/PyCQA/isort
    rev: v0.800
    hooks:
    -   id: mypy
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint  
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
    -   id: isort